"""
FlowForge AI — Export Service

Generates downloadable reports in multiple formats:
  • Markdown (.md)
  • PDF Document (.pdf)
  • Microsoft Word (.docx)
"""

from __future__ import annotations

import io
import json
from typing import Any

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from models.workflow import Workflow

STAGE_TITLES = {
    "requirements": "Stage 1 — Requirements Analysis",
    "design": "Stage 2 — Solution Design & Architecture",
    "implementation": "Stage 3 — Implementation Planning",
    "review": "Stage 4 — Code Review & Security Audit",
}


def _safe_json(raw: str) -> dict:
    """Attempt to parse JSON, return raw text wrapper on failure."""
    try:
        data = json.loads(raw)
        return data if isinstance(data, dict) else {"raw": str(data)}
    except (json.JSONDecodeError, TypeError):
        return {"raw_output": raw}


def _unwrap_stage_output(stage_name: str, data: dict) -> dict:
    """Unwrap nested node dictionary if present."""
    if isinstance(data, dict) and stage_name in data and isinstance(data[stage_name], dict):
        return data[stage_name]
    return data


# ── 1. MARKDOWN EXPORT ───────────────────────────────────────────────

def _render_md_section(title: str, data: dict, level: int = 2) -> str:
    """Recursively render a dict/list as Markdown."""
    lines: list[str] = []
    prefix = "#" * level

    lines.append(f"{prefix} {title}\n")

    for key, value in data.items():
        nice_key = key.replace("_", " ").title()
        if isinstance(value, str):
            lines.append(f"**{nice_key}:** {value}\n")
        elif isinstance(value, list):
            lines.append(f"**{nice_key}:**\n")
            for item in value:
                if isinstance(item, dict):
                    parts = []
                    for k, v in item.items():
                        if isinstance(v, list):
                            v = ", ".join(str(i) for i in v)
                        parts.append(f"{k.replace('_', ' ').title()}: {v}")
                    lines.append(f"- {' | '.join(parts)}")
                else:
                    lines.append(f"- {item}")
            lines.append("")
        elif isinstance(value, dict):
            lines.append(f"**{nice_key}:**\n")
            for k, v in value.items():
                if isinstance(v, dict):
                    inner = ", ".join(f"{ik}: {iv}" for ik, iv in v.items())
                    lines.append(f"- **{k}**: {inner}")
                else:
                    lines.append(f"- **{k}**: {v}")
            lines.append("")

    return "\n".join(lines)


def generate_markdown_report(workflow: Workflow) -> str:
    """Generate a comprehensive Markdown report from a workflow."""
    lines: list[str] = []

    lines.append("# FlowForge AI — Autonomous Feature Delivery Plan\n")
    lines.append(f"**Workflow ID:** `{workflow.id}`  ")
    lines.append(f"**Status:** {workflow.status.upper()}  ")
    lines.append(f"**Created At:** {workflow.created_at}  ")
    lines.append(f"**Updated At:** {workflow.updated_at}\n")

    lines.append("## Feature Request\n")
    lines.append(f"> {workflow.feature_request}\n")
    lines.append("---\n")

    for stage in sorted(workflow.stages, key=lambda s: s.order_index):
        title = STAGE_TITLES.get(stage.stage_name, stage.stage_name.title())
        lines.append(f"## {title}\n")
        lines.append(f"**Status:** {stage.status.upper()}  ")

        if stage.duration_seconds is not None and stage.duration_seconds > 0:
            lines.append(f"**Execution Duration:** {stage.duration_seconds:.2f}s  ")

        if stage.error_message:
            lines.append(f"\n⚠️ **Error:** {stage.error_message}\n")

        if stage.output and stage.output != "{}":
            data = _unwrap_stage_output(stage.stage_name, _safe_json(stage.output))
            lines.append("")
            lines.append(_render_md_section("Stage Deliverables", data, level=3))

        lines.append("---\n")

    lines.append("\n*Generated by FlowForge AI — Autonomous Multi-Agent Orchestration*")
    return "\n".join(lines)


# ── 2. WORD (.DOCX) EXPORT ──────────────────────────────────────────

def generate_docx_report(workflow: Workflow) -> bytes:
    """Generate a formatted Microsoft Word (.docx) document."""
    doc = Document()

    # Page Margins
    for section in doc.sections:
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)
        section.left_margin = Inches(0.8)
        section.right_margin = Inches(0.8)

    # Document Header
    title_p = doc.add_heading("FlowForge AI", level=0)
    title_p.runs[0].font.color.rgb = RGBColor(6, 182, 212)  # Cyan

    sub_p = doc.add_paragraph("Autonomous Feature Delivery & Multi-Agent Architecture Plan")
    sub_p.runs[0].font.size = Pt(13)
    sub_p.runs[0].font.italic = True

    # Metadata Table
    table = doc.add_table(rows=3, cols=2)
    table.style = "Light Shading Accent 1" if "Light Shading Accent 1" in [s.name for s in doc.styles] else "Table Grid"
    rows = table.rows
    rows[0].cells[0].text = "Workflow ID"
    rows[0].cells[1].text = str(workflow.id)
    rows[1].cells[0].text = "Pipeline Status"
    rows[1].cells[1].text = str(workflow.status).upper()
    rows[2].cells[0].text = "Generated At"
    rows[2].cells[1].text = str(workflow.created_at)

    doc.add_paragraph()  # Spacing

    # Feature Request Callout
    doc.add_heading("Feature Request", level=1)
    req_p = doc.add_paragraph(workflow.feature_request)
    req_p.style = "Intense Quote" if "Intense Quote" in [s.name for s in doc.styles] else "Normal"

    doc.add_paragraph()

    # Stages
    for stage in sorted(workflow.stages, key=lambda s: s.order_index):
        title = STAGE_TITLES.get(stage.stage_name, stage.stage_name.title())
        h = doc.add_heading(title, level=1)
        h.runs[0].font.color.rgb = RGBColor(99, 102, 241)  # Indigo

        status_line = f"Status: {stage.status.upper()}"
        if stage.duration_seconds and stage.duration_seconds > 0:
            status_line += f"  |  Duration: {stage.duration_seconds:.2f}s"
        doc.add_paragraph(status_line)

        if stage.output and stage.output != "{}":
            data = _unwrap_stage_output(stage.stage_name, _safe_json(stage.output))

            for key, val in data.items():
                nice_key = key.replace("_", " ").title()
                if isinstance(val, str):
                    doc.add_heading(nice_key, level=2)
                    doc.add_paragraph(val)
                elif isinstance(val, list):
                    doc.add_heading(nice_key, level=2)
                    for item in val:
                        if isinstance(item, dict):
                            line = " | ".join(f"{k.replace('_', ' ').title()}: {v}" for k, v in item.items() if not isinstance(v, (dict, list)))
                            doc.add_paragraph(line, style="List Bullet")
                        else:
                            doc.add_paragraph(str(item), style="List Bullet")
                elif isinstance(val, dict):
                    doc.add_heading(nice_key, level=2)
                    for sub_k, sub_v in val.items():
                        if isinstance(sub_v, dict):
                            inner_desc = ", ".join(f"{ik}: {iv}" for ik, iv in sub_v.items())
                            doc.add_paragraph(f"{sub_k.title()}: {inner_desc}", style="List Bullet")
                        else:
                            doc.add_paragraph(f"{sub_k.title()}: {sub_v}", style="List Bullet")

        doc.add_paragraph()  # Spacing between stages

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── 3. PDF EXPORT ───────────────────────────────────────────────────

def generate_pdf_report(workflow: Workflow) -> bytes:
    """Generate a publication-grade PDF document."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    base_styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=base_styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=26,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=base_styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=14,
    )
    h1_style = ParagraphStyle(
        "StageHeading",
        parent=base_styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#4338ca"),
        spaceBefore=12,
        spaceAfter=4,
    )
    h2_style = ParagraphStyle(
        "SubHeading",
        parent=base_styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=6,
        spaceAfter=2,
    )
    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=base_styles["BodyText"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#334155"),
        spaceAfter=4,
    )
    bullet_style = ParagraphStyle(
        "BulletCustom",
        parent=body_style,
        leftIndent=12,
        firstLineIndent=-8,
        spaceAfter=2,
    )

    story = []

    # Title & Subtitle
    story.append(Paragraph("FlowForge AI — Feature Delivery Plan", title_style))
    story.append(Paragraph("Multi-Agent Autonomous Engineering Architecture Specification", subtitle_style))

    # Meta Table
    meta_data = [
        [Paragraph("<b>Workflow ID:</b>", body_style), Paragraph(str(workflow.id), body_style)],
        [Paragraph("<b>Status:</b>", body_style), Paragraph(str(workflow.status).upper(), body_style)],
        [Paragraph("<b>Generated:</b>", body_style), Paragraph(str(workflow.created_at)[:19], body_style)],
    ]
    meta_table = Table(meta_data, colWidths=[100, 440])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#e2e8f0")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # Feature Request
    story.append(Paragraph("<b>Feature Request:</b>", h2_style))
    # Escape xml entities for ReportLab
    safe_req = str(workflow.feature_request).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    story.append(Paragraph(f"<i>&ldquo;{safe_req}&rdquo;</i>", body_style))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceAfter=8))

    # Stages
    for stage in sorted(workflow.stages, key=lambda s: s.order_index):
        title = STAGE_TITLES.get(stage.stage_name, stage.stage_name.title())
        story.append(Paragraph(title, h1_style))

        dur_text = f" | Duration: {stage.duration_seconds:.2f}s" if (stage.duration_seconds and stage.duration_seconds > 0) else ""
        story.append(Paragraph(f"<b>Status:</b> {stage.status.upper()}{dur_text}", body_style))

        if stage.output and stage.output != "{}":
            data = _unwrap_stage_output(stage.stage_name, _safe_json(stage.output))

            for key, val in data.items():
                nice_key = key.replace("_", " ").title()
                story.append(Paragraph(f"<b>{nice_key}</b>", h2_style))

                if isinstance(val, str):
                    clean_str = val.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    story.append(Paragraph(clean_str, body_style))
                elif isinstance(val, list):
                    for item in val[:6]:  # Keep PDF compact
                        if isinstance(item, dict):
                            parts = []
                            for k, v in item.items():
                                if isinstance(v, (str, int, float)):
                                    parts.append(f"<b>{k.replace('_', ' ').title()}:</b> {v}")
                            clean_line = " &bull; ".join(parts).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                            story.append(Paragraph(f"&bull; {clean_line}", bullet_style))
                        else:
                            clean_line = str(item).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                            story.append(Paragraph(f"&bull; {clean_line}", bullet_style))
                elif isinstance(val, dict):
                    for sk, sv in list(val.items())[:6]:
                        clean_sk = str(sk).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                        clean_sv = str(sv).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                        story.append(Paragraph(f"&bull; <b>{clean_sk}:</b> {clean_sv}", bullet_style))

        story.append(Spacer(1, 6))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=6))

    doc.build(story)
    return buf.getvalue()
